const STORY_DATA = {
  title: '绯衣鬼戏',
  subtitle: '大理寺司案沈清和的第一案',
  caseId: 'case-001',
  acts: [
    {
      id: 'prologue',
      title: '三个月前',
      summary:
        '新证据证明当年判决有误，沈氏失去圣心。一个月前，长公主举荐沈清和入大理寺任司案。',
    },
    {
      id: 'opening-night',
      title: '今夜',
      summary:
        '长安名伶谢无咎在倚云楼戏台上倒下，众人说是三年前的绯衣女鬼回来索命。',
    },
  ],
  scenes: [
    {
      id: 'stage-open',
      title: '绮云楼 · 戏台',
      placeLabel: '红幕半垂的戏台',
      palette: ['#372026', '#7d2633', '#d7ad6f'],
      notes: ['后台铜镜微晃', '红衣鬼影一闪', '男伶倒在台中央'],
      steps: [
        { type: 'dialog', speaker: '女伶', text: '你负我三年，今日可敢回头看我？' },
        { type: 'dialog', speaker: '男伶', text: '人死如灯灭，哪来的鬼！' },
        {
          type: 'narration',
          text:
            '一侧幕布没拉好，后台铜镜微微一晃，红衣鬼影一闪出现。台上男伶忽然捂住喉咙，倒在戏台上。',
        },
        { type: 'dialog', speaker: '宾客', text: '好！谢大家这一倒跟真的似的！' },
        { type: 'dialog', speaker: '女伶', text: '谢郎？' },
        { type: 'narration', text: '后台传来尖叫。' },
        { type: 'dialog', speaker: '小伶人', text: '镜里有人！绯衣娘子回来了！' },
      ],
    },
    {
      id: 'front-door',
      title: '倚云楼 · 门口',
      placeLabel: '灯影摇晃的大门',
      palette: ['#1f2f36', '#b44a3c', '#e2c48c'],
      notes: ['大门半掩', '掌柜拦路', '寺牒在袖'],
      steps: [
        {
          type: 'dialog',
          speaker: '沈清和',
          text: '我叫沈清和，一个月前，我从公主府被调入大理寺，任职司案。',
        },
        {
          type: 'dialog',
          speaker: '沈清和',
          text: '今夜，长安最有名的男伶谢无咎，在倚云楼死在满堂宾客眼前。',
        },
        {
          type: 'dialog',
          speaker: '沈清和',
          text: '有人说，他不是被人杀的，是三年前死在这里的绯衣女鬼，回来索命了。',
        },
        {
          type: 'narration',
          text: '昭雪从沈清和袖中探出头，像是也闻到了案子的味道。',
        },
        {
          type: 'dialog',
          speaker: '沈清和',
          text: '昭雪，走。我们进去看看，杀他的到底是人，还是“鬼”。',
        },
        {
          type: 'hotspot',
          prompt: '点击大门靠近',
          hotspots: [
            {
              id: 'half-open-door',
              label: '推开大门',
              x: 0.34,
              y: 0.2,
              w: 0.32,
              h: 0.44,
              result: [
                { speaker: '掌柜', text: '女郎留步，今夜楼中出了些小乱，不便待客。' },
                { speaker: '沈清和', text: '大理寺司案，沈清和。奉寺牒勘验命案。' },
                { speaker: '掌柜', text: '这……这……' },
                {
                  speaker: '掌柜',
                  text: '楼里多是贵客，若传出去说闹出人命，小楼的招牌就——',
                },
                {
                  speaker: '沈清和',
                  text: '招牌若比人命要紧，你现在就可以跟我回大理寺解释。',
                },
                { speaker: '掌柜', text: '小人不敢！大人随我进去吧。' },
              ],
              next: true,
            },
          ],
        },
        {
          type: 'hotspot',
          prompt: '点击大门进入戏台',
          hotspots: [
            {
              id: 'enter-stage',
              label: '进入倚云楼',
              x: 0.28,
              y: 0.16,
              w: 0.44,
              h: 0.5,
              result: [{ speaker: '掌柜', text: '沈司案，人就在台上。小人们什么都没敢动。' }],
              advanceBeforeResult: true,
              next: true,
            },
          ],
        },
      ],
    },
    {
      id: 'body-check',
      title: '倚云楼 · 戏台',
      placeLabel: '谢无咎倒在台中央',
      palette: ['#221e24', '#872a34', '#d5c4a1'],
      notes: ['红幕半垂', '锣鼓歪倒', '尸身覆着白布'],
      steps: [
        { type: 'dialog', speaker: '沈清和', text: '嗯，我先看看尸体。' },
        {
          type: 'inspect',
          prompt: '勘验尸体上的三个疑点',
          completeText: '疑点已全部收集',
          hotspots: [
            {
              id: 'throat',
              label: '喉间',
              x: 0.46,
              y: 0.33,
              w: 0.12,
              h: 0.08,
              clue: '喉间发黑，却没有指痕或勒痕。',
              result: [
                { speaker: '沈清和', text: '喉间发黑。远看确实像被什么东西掐住。' },
                { speaker: '掌柜', text: '是啊！楼里的人都说，这是绯衣娘子回来索命！' },
                { speaker: '沈清和', text: '可脖子上没有指痕，也没有勒痕。' },
              ],
            },
            {
              id: 'lapel',
              label: '衣襟',
              x: 0.39,
              y: 0.48,
              w: 0.12,
              h: 0.09,
              clue: '衣襟内侧有细粉，颜色发黑。',
              result: [
                { speaker: '沈清和', text: '昭雪，来，闻闻。' },
                { speaker: '画面', text: '昭雪凑近衣襟闻了闻，不屑地转开头。' },
                { speaker: '掌柜', text: '伶人上台都要熏香扑粉，味道杂些也正常吧？' },
                { speaker: '沈清和', text: '嘘——不对，衣襟内侧有细粉，颜色发黑。' },
              ],
            },
            {
              id: 'right-hand',
              label: '右手',
              x: 0.62,
              y: 0.49,
              w: 0.12,
              h: 0.09,
              clue: '右手掌心有压痕，死前似乎攥过耳坠。',
              result: [
                { speaker: '沈清和', text: '右手指节僵硬，掌心有压痕。他死前手里攥着东西？' },
                { speaker: '掌柜', text: '一枚耳坠……绯衣娘子的耳坠。可后来一乱，就不知落到哪里去了。' },
                { speaker: '沈清和', text: '偏偏是死人手里的东西不见了…' },
              ],
            },
          ],
          after: [
            { speaker: '掌柜', text: '沈司案，查到什么了吗?' },
            {
              speaker: '沈清和',
              text: '你们这没闹鬼，他也只是被人刻意做成了“鬼掐喉”的样子。',
            },
          ],
        },
        {
          type: 'hotspot',
          prompt: '昭雪发现木板缝隙中有东西',
          hotspots: [
            {
              id: 'floor-gap',
              label: '木板缝隙',
              x: 0.18,
              y: 0.58,
              w: 0.64,
              h: 0.11,
              result: [
                { speaker: '沈清和', text: '昭雪，下面有东西？' },
                { speaker: '沈清和', text: '你这小胖爪可伸不进去，让我来吧。' },
              ],
              next: true,
            },
          ],
        },
        {
          type: 'merge',
          title: '锦囊合成',
          prompt: '把零散线索合成可取物的长柄竹镊',
          startItem: '扇骨',
          chain: ['扇骨', '结实的竹片', '缠了布条当手柄的竹条', '长柄竹镊'],
          submitText: '用取物夹探入木缝',
          resultItem: '耳坠',
          after: [
            { speaker: '画面', text: '竹镊探进地板木缝，伸出来时，末端夹着一枚耳坠。' },
            { speaker: '掌柜', text: '这、这是绯衣娘子的耳坠！' },
            { speaker: '沈清和', text: '耳坠边缘有撬痕，被人打开过。' },
            { speaker: '掌柜', text: '耳坠还能打开？' },
            {
              speaker: '沈清和',
              text: '有些首饰会特地做成空心的，用来藏香、藏药。打开看看就知道了。',
            },
          ],
        },
        {
          type: 'merge',
          title: '打开耳坠',
          prompt: '继续合成工具，取出耳坠里的残留物',
          startItem: '绣花针',
          chain: ['绣花针', '手帕', '凿子', '一撮黑色粉末'],
          submitText: '撬开耳坠暗格',
          resultItem: '一撮黑色粉末',
          after: [
            { speaker: '沈清和', text: '耳坠里残留的粉末和谢无咎衣襟里的黑粉是同一种。' },
            {
              speaker: '掌柜',
              text: '真是疯了！这可是绯衣娘子的遗物啊，谁敢对它做手脚，也不怕被冤魂缠上！',
            },
            {
              speaker: '沈清和',
              text: '我也好奇是谁在“借鬼杀人”。这楼里的伶人、乐工、杂役…掌柜你也有可能嘛。',
            },
            { speaker: '掌柜', text: '司案可别吓我了，哈…哈哈…' },
            { speaker: '沈清和', text: '走吧，我们去戏台后面，问问那面铜镜里的鬼影。' },
          ],
        },
      ],
    },
    {
      id: 'backstage-door',
      title: '倚云楼 · 出将门',
      placeLabel: '半落的门帘',
      palette: ['#17191f', '#5b1824', '#b08c59'],
      notes: ['帘面绣着“出将”', '门后全黑', '铜镜疑云未解'],
      steps: [
        {
          type: 'hotspot',
          prompt: '点击戏台侧边的出将门',
          hotspots: [
            {
              id: 'backstage',
              label: '靠近门帘',
              x: 0.34,
              y: 0.18,
              w: 0.32,
              h: 0.48,
              result: [
                {
                  speaker: '画面',
                  text: '门帘掉了一半，帘面上绣着“出将”。没有门帘遮挡的门洞黑得看不见底。',
                },
              ],
              next: true,
            },
          ],
        },
        {
          type: 'ending',
          title: '第一章结束',
          text: '第一关结束。下一步将进入后台，追查铜镜中的鬼影。',
        },
      ],
    },
  ],
};

const CHAPTER_TWO = {
  id: 'chapter-2',
  title: '第二章 · 后台戏房',
  subtitle: '追查铜镜鬼影与谢无咎专座线索',
  placeLabel: '灯火低暗的后台戏房',
  scenes: [
    {
      id: 'backstage-room-entry',
      title: '倚云楼 · 戏房',
      placeLabel: '脂粉、戏服与倾倒妆台之间',
      visual: 'ch2-backstage-room',
      palette: ['#2b1c18', '#7d3f2e', '#d6a15e'],
      notes: ['妆台倾倒', '鬼面悬墙', '铜锣靠墙'],
      steps: [
        { type: 'dialog', speaker: '掌柜', text: '沈司案慢些走。仔细绊脚。' },
        { type: 'dialog', speaker: '掌柜', text: '方才台上一乱，人人都往后跑。您看这屋子，哪还有查得清的样子？' },
        { type: 'dialog', speaker: '玩家', text: '怎么，不想让我查？查不清，和不想让人查清，是两回事。' },
        { type: 'dialog', speaker: '掌柜', text: '……沈司案说笑了。' },
        { type: 'dialog', speaker: '玩家', text: '既然没有落脚的地，那就辛苦掌柜帮我腾条路出来。' },
        {
          type: 'hotspot',
          prompt: '先整理脚边的妆台',
          hotspots: [
            {
              id: 'vanity-table',
              label: '扶起妆台',
              x: 0.18,
              y: 0.42,
              w: 0.24,
              h: 0.16,
              result: [
                { speaker: '画面', text: '妆台被扶起归位，桌面脂粉散了一片。昭雪从袖中探出上半身，贴着桌沿闻了闻。' },
                { speaker: '玩家', text: '昭雪这是闻见什么了？' },
                { speaker: '昭雪', text: '吱。' },
                { speaker: '玩家', text: '要是真找到什么，今晚就给你加餐！' },
              ],
              next: true,
            },
          ],
        },
        {
          type: 'hotspot',
          prompt: '查看墙上的鬼脸面具',
          hotspots: [
            {
              id: 'ghost-mask',
              label: '鬼脸面具',
              x: 0.52,
              y: 0.2,
              w: 0.2,
              h: 0.14,
              result: [
                { speaker: '画面', text: '半张惨白鬼脸面具松动，啪嗒一声掉到地上。' },
                { speaker: '昭雪', text: '吱！' },
                { speaker: '玩家', text: '这么胆小，还敢先钻进来。' },
                { speaker: '玩家', text: '……哦，也不算胆小。就是讨厌装神弄鬼的东西。' },
                { speaker: '玩家', text: '倚云楼不愧是长安第一楼，连傩戏也有。' },
                { speaker: '掌柜', text: '沈司案误会了，这面具是吓小伶人的玩意儿，不值钱。' },
                { speaker: '掌柜', text: '后台孩子多，爱偷懒。挂个鬼脸，省得他们乱钻。' },
              ],
              next: true,
            },
          ],
        },
        {
          type: 'hotspot',
          prompt: '查看墙边铜锣',
          hotspots: [
            {
              id: 'cue-gong',
              label: '催场铜锣',
              x: 0.12,
              y: 0.56,
              w: 0.22,
              h: 0.14,
              result: [
                { speaker: '玩家', text: '戏房不是换行头的地方么，怎么会有个锣？' },
                { speaker: '掌柜', text: '这是催场的铜锣。最后一折催场，要响三声。' },
                { speaker: '掌柜', text: '第二声候场，第三声上台。都是老规矩。' },
                { speaker: '玩家', text: '谢无咎就是死在最后一折吧？这锣声也响过？' },
                { speaker: '掌柜', text: '是，最后一声响起，女鬼就该登场了。结果…' },
              ],
              next: true,
            },
          ],
        },
        {
          type: 'hotspot',
          prompt: '敲一次锣听个响',
          hotspots: [
            {
              id: 'strike-gong',
              label: '敲锣',
              x: 0.12,
              y: 0.56,
              w: 0.22,
              h: 0.14,
              result: [
                { speaker: '画面', text: '锣声一响，墙边收纳戏服的木箱轻轻动了一下。' },
                { speaker: '掌柜', text: '噫——！！！鬼——' },
                { speaker: '玩家', text: '谁在那里？' },
                { speaker: '画面', text: '昭雪钻了过去，前爪扶着木箱闻嗅。一个十二三岁的小伶女从箱后探出半张脸。' },
                { speaker: '小乙', text: '别、别让它咬我！' },
                { speaker: '玩家', text: '它不咬人，但我看你们掌柜被吓得要打人了。' },
                { speaker: '玩家', text: '出来吧。站那儿别动，不问你案子。' },
              ],
              next: true,
            },
          ],
        },
      ],
    },
    {
      id: 'backstage-xie-seat',
      title: '倚云楼 · 谢无咎专座',
      placeLabel: '长凳、茶盏与半枚润嗓梅',
      visual: 'ch2-xie-seat-props',
      palette: ['#241d1c', '#75422e', '#d4a66a'],
      notes: ['小乙现身', '长凳专座', '茶盏冷透'],
      steps: [
        {
          type: 'hotspot',
          prompt: '询问躲在木箱后的孩子',
          hotspots: [
            {
              id: 'ask-xiaoyi',
              label: '问小乙',
              x: 0.62,
              y: 0.42,
              w: 0.2,
              h: 0.22,
              result: [
                { speaker: '玩家', text: '你叫什么？' },
                { speaker: '小乙', text: '小乙。' },
                { speaker: '玩家', text: '你一直在这儿？' },
                { speaker: '小乙', text: '嗯…我听见有人喊有鬼…我不敢出去。' },
                { speaker: '玩家', text: '你怕鬼？' },
                { speaker: '小乙', text: '大人，哪个小孩不怕鬼呀！' },
                { speaker: '玩家', text: '最会吓人的，未必是鬼。' },
              ],
              next: true,
            },
          ],
        },
        {
          type: 'hotspot',
          prompt: '整理倒下的木凳',
          hotspots: [
            {
              id: 'fallen-stool',
              label: '扶起木凳',
              x: 0.18,
              y: 0.6,
              w: 0.22,
              h: 0.12,
              result: [{ speaker: '画面', text: '倒下的木凳被扶起，旁边一条长凳露了出来。' }],
              next: true,
            },
          ],
        },
        {
          type: 'hotspot',
          prompt: '查看谢无咎常坐的长凳',
          hotspots: [
            {
              id: 'xie-bench',
              label: '长凳',
              x: 0.42,
              y: 0.58,
              w: 0.36,
              h: 0.12,
              result: [
                { speaker: '玩家', text: '这是不是谢无咎的位置？' },
                { speaker: '小乙', text: '嗯。他每次都坐这，也没人敢跟他坐一起。' },
                { speaker: '玩家', text: '为什么不敢，他对你们很凶吗？' },
                { speaker: '小乙', text: '不是…他从来不骂我们，可他看人一眼，比骂人还吓人。' },
                { speaker: '玩家', text: '今晚他也坐这里？' },
                { speaker: '小乙', text: '坐了好久。夜戏还没点灯他就来了。' },
              ],
              next: true,
            },
          ],
        },
        {
          type: 'inspect',
          prompt: '逐一查看长凳上的三样东西',
          completeText: '谢无咎专座线索已收集',
          hotspots: [
            {
              id: 'plum',
              label: '润嗓梅',
              x: 0.46,
              y: 0.52,
              w: 0.12,
              h: 0.08,
              clue: '半枚润嗓梅有清楚牙印。',
              result: [
                { speaker: '画面', text: '半枚润嗓梅落在茶盏旁，果肉被咬开，牙印清楚。' },
                { speaker: '小乙', text: '这个我知道！唱高腔前吃的，酸酸甜甜。' },
                { speaker: '玩家', text: '今晚是谁送来的润嗓梅？' },
                { speaker: '小乙', text: '戏房的果脯盒子里一直都备着，只不让我们小孩吃。' },
              ],
            },
            {
              id: 'tea',
              label: '茶盏',
              x: 0.58,
              y: 0.52,
              w: 0.12,
              h: 0.08,
              clue: '茶盏已冷，盏底有细小黑渣。',
              result: [
                { speaker: '画面', text: '茶已经冷了，盏底沉着细小黑渣。昭雪凑近嗅了一下，立刻后退。' },
                { speaker: '玩家', text: '茶也是戏房会一直备着的？' },
                { speaker: '掌柜', text: '是，多是冷茶，谁渴了就自己倒。' },
                { speaker: '玩家', text: '谢无咎这种头牌，也自己倒茶？' },
                { speaker: '掌柜', text: '他脾气怪，有时不让人近身。' },
              ],
            },
            {
              id: 'sweat-cloth',
              label: '汗巾',
              x: 0.7,
              y: 0.52,
              w: 0.12,
              h: 0.08,
              clue: '汗巾皱湿，谢无咎今夜很紧张。',
              result: [
                { speaker: '画面', text: '汗巾有湿痕，皱巴巴，像是被握在手里很久。' },
                { speaker: '玩家', text: '这条汗巾他攥过很久，还出了不少手汗。' },
                { speaker: '掌柜', text: '戏服厚，热出汗也正常。' },
                { speaker: '小乙', text: '戏房里很闷的。' },
                { speaker: '画面', text: '线索：今夜的谢无咎很紧张。' },
              ],
            },
          ],
          after: [
            { speaker: '画面', text: '灯盏火苗忽明忽暗，整个戏房的亮度暗了一半。' },
          ],
        },
        {
          type: 'hotspot',
          prompt: '查看桌上快灭的灯盏',
          hotspots: [
            {
              id: 'oil-lamp',
              label: '灯盏',
              x: 0.18,
              y: 0.27,
              w: 0.18,
              h: 0.12,
              result: [
                { speaker: '掌柜', text: '哎哟，沈司案你看这乱的，连灯油没了都没人发现。小乙你去取点灯油来。' },
                { speaker: '小乙', text: '是，掌柜。' },
                { speaker: '画面', text: '片刻过后，小乙带来灯油。灯油倒进灯盏，画面恢复明亮。' },
                { speaker: '玩家', text: '这灯油今晚添过吗？' },
                { speaker: '小乙', text: '还没来得及添灯油，就、就发生了那事……' },
                { speaker: '小乙', text: '今晚贵客多，掌柜还嘱咐我们换上了好灯油、早早点灯呢，放平日哪烧得到现在。' },
                { speaker: '画面', text: '意识到说错话，小乙立刻捂住嘴。' },
              ],
              next: true,
            },
          ],
        },
      ],
    },
    {
      id: 'backstage-props',
      title: '倚云楼 · 道具架',
      placeLabel: '鬼铃、血包与走位板',
      visual: 'ch2-prop-rack-red-mud',
      palette: ['#211719', '#65312f', '#c99058'],
      notes: ['戏鞋红泥', '血包将空', '走位被改'],
      steps: [
        {
          type: 'hotspot',
          prompt: '灯亮后查看长凳下方鞋痕',
          hotspots: [
            {
              id: 'scuff-mark',
              label: '鞋痕',
              x: 0.44,
              y: 0.68,
              w: 0.26,
              h: 0.08,
              result: [
                { speaker: '玩家', text: '谢无咎坐在这里，一直在蹭地。' },
                { speaker: '小乙', text: '无咎哥哥有时就这样。' },
                { speaker: '小乙', text: '他背词的时候。背到不喜欢的地方，就蹭一下。' },
                { speaker: '玩家', text: '今晚他背词了？' },
                { speaker: '小乙', text: '没听清。他像是在念，又像是在忍着不念。' },
              ],
              next: true,
            },
          ],
        },
        {
          type: 'hotspot',
          prompt: '查看地上的黑缎戏鞋',
          hotspots: [
            {
              id: 'black-shoe',
              label: '黑缎戏鞋',
              x: 0.2,
              y: 0.66,
              w: 0.22,
              h: 0.1,
              result: [
                { speaker: '玩家', text: '这鞋是谁的？' },
                { speaker: '掌柜', text: '后台戏鞋多，都是上场的时候随便穿的，难以辨认。' },
                { speaker: '玩家', text: '谢无咎也穿这种鞋？' },
                { speaker: '掌柜', text: '他是头牌，自有自己的戏鞋。不会和旁人混。' },
                { speaker: '玩家', text: '嗯，这只鞋先交给我。' },
                { speaker: '画面', text: '获得物证：一只沾着暗红色泥的戏鞋。' },
              ],
              item: '戏鞋',
              next: true,
            },
          ],
        },
        {
          type: 'hotspot',
          prompt: '查看倒下的道具架',
          hotspots: [
            {
              id: 'prop-rack',
              label: '道具架',
              x: 0.48,
              y: 0.28,
              w: 0.28,
              h: 0.26,
              result: [
                { speaker: '画面', text: '木剑、红烛、血书和鬼铃堆在一起。最下层有个小木匣，被半张鬼面压住。' },
                { speaker: '画面', text: '昭雪从架子底下钻进去，尾巴一扫，把鬼面推开，拖出小木匣。' },
                { speaker: '小乙', text: '它好厉害。' },
                { speaker: '昭雪', text: '吱！' },
                { speaker: '玩家', text: '厉害是厉害，就是不太守规矩。' },
                { speaker: '昭雪', text: '吱！' },
              ],
              next: true,
            },
          ],
        },
        {
          type: 'hotspot',
          prompt: '打开小木匣',
          hotspots: [
            {
              id: 'blood-box',
              label: '血包木匣',
              x: 0.58,
              y: 0.55,
              w: 0.18,
              h: 0.12,
              result: [
                { speaker: '画面', text: '小木匣打开，里面只剩几枚血包。' },
                { speaker: '玩家', text: '这是什么？' },
                { speaker: '小乙', text: '血包，含在嘴里用的。' },
                { speaker: '掌柜', text: '这出戏用得多。女鬼、负心郎、群伶都要吐血，我让人备了满满一匣子呢。' },
                { speaker: '玩家', text: '你们这戏挺费血。' },
                { speaker: '小乙', text: '是呀，吐血量大的角儿要含两三个才够呢。' },
                { speaker: '画面', text: '线索：谢无咎曾经含过匣子里的血包。' },
              ],
              next: true,
            },
          ],
        },
        {
          type: 'hotspot',
          prompt: '查看鬼铃',
          hotspots: [
            {
              id: 'ghost-bell',
              label: '鬼铃',
              x: 0.75,
              y: 0.34,
              w: 0.12,
              h: 0.14,
              result: [
                { speaker: '小乙', text: '姜师傅说女鬼出场前摇响鬼铃，可以听取哇声一片。' },
                { speaker: '玩家', text: '你不怕？' },
                { speaker: '小乙', text: '我以前怕。可是听姜师傅说，沈绯姐姐演女鬼时，从不吓小孩。' },
                { speaker: '玩家', text: '为什么？' },
                { speaker: '小乙', text: '她说小孩胆子是慢慢长的，吓坏了就长歪了。' },
                { speaker: '玩家', text: '她对你们很好？' },
                { speaker: '小乙', text: '我没见过她。可大家都这么说。' },
              ],
              next: true,
            },
          ],
        },
        {
          type: 'hotspot',
          prompt: '查看墙上的走位板',
          hotspots: [
            {
              id: 'blocking-board',
              label: '走位板',
              x: 0.24,
              y: 0.22,
              w: 0.26,
              h: 0.18,
              result: [
                { speaker: '画面', text: '木板上画着戏台方位。朱笔标出最后一折走位：谢无咎立在台心，绯萤的出场线被改过。' },
                { speaker: '玩家', text: '这处改动是谁定的？' },
                { speaker: '掌柜', text: '绯萤提过几句。她学沈绯衣学得像，对这出戏有心。' },
                { speaker: '玩家', text: '绯萤？' },
                { speaker: '小乙', text: '就是今晚演绯衣女鬼的女伶，绯萤姐姐真倒霉，刚回楼里就遇到了这种事。' },
                { speaker: '玩家', text: '回楼…她以前就在倚云楼？' },
                { speaker: '掌柜', text: '只不过小时候在楼里待过。后来被一个老琴师带走了，前阵子才回来。' },
              ],
              next: true,
            },
          ],
        },
        {
          type: 'hotspot',
          prompt: '追问小乙走位改动',
          hotspots: [
            {
              id: 'xiaoyi-route',
              label: '追问小乙',
              x: 0.62,
              y: 0.42,
              w: 0.2,
              h: 0.22,
              result: [
                { speaker: '玩家', text: '木板上这条新的走位，是绯萤改的？' },
                { speaker: '小乙', text: '嗯。她说这里不能直走，要绕半步，再回头。' },
                { speaker: '玩家', text: '她有说为什么吗？' },
                { speaker: '小乙', text: '她说…沈绯衣姐姐当年就是这样走的，大家都不敢细问。' },
                { speaker: '玩家', text: '谢无咎知道这处改动吗？' },
                { speaker: '小乙', text: '知道。他当时看着这块板，笑了一下。' },
                { speaker: '玩家', text: '笑？他是怎么笑的？' },
                { speaker: '小乙', text: '不像高兴。像…像是他早知道会这样。' },
                { speaker: '玩家', text: '这就有趣了。' },
              ],
              next: true,
            },
          ],
        },
      ],
    },
    {
      id: 'backstage-deduction',
      title: '倚云楼 · 暂歇',
      placeLabel: '掌柜带走小乙后的短暂空隙',
      visual: 'ch2-xie-seat-props',
      palette: ['#1d1a1d', '#55322e', '#b98b5f'],
      notes: ['掌柜打断', '糯米纸', '证物归桌'],
      steps: [
        {
          type: 'hotspot',
          prompt: '再问问小乙其他线索',
          hotspots: [
            {
              id: 'more-clues',
              label: '小乙',
              x: 0.62,
              y: 0.42,
              w: 0.2,
              h: 0.22,
              result: [
                { speaker: '掌柜', text: '咳咳……' },
                { speaker: '掌柜', text: '沈司案，您若要细看，先喝口茶也无妨。' },
                { speaker: '玩家', text: '我不渴。' },
                { speaker: '掌柜', text: '后台乱，东西也多。您这一路翻过去，怕是累。' },
                { speaker: '玩家', text: '掌柜倒体贴。那就先缓一缓。' },
              ],
              next: true,
            },
          ],
        },
        {
          type: 'hotspot',
          prompt: '坐下休息一会',
          hotspots: [
            {
              id: 'rest-chair',
              label: '椅子',
              x: 0.16,
              y: 0.58,
              w: 0.2,
              h: 0.16,
              result: [
                { speaker: '掌柜', text: '我去让人给沈司案沏壶好茶。小乙，跟我去端茶。' },
                { speaker: '画面', text: '掌柜带着小乙离开了戏房。' },
                { speaker: '玩家', text: '看来掌柜不想让我继续查下去…' },
              ],
              next: true,
            },
          ],
        },
        {
          type: 'hotspot',
          prompt: '趁没人查看谢无咎的长凳',
          hotspots: [
            {
              id: 'rice-paper',
              label: '糯米纸',
              x: 0.43,
              y: 0.55,
              w: 0.28,
              h: 0.1,
              result: [
                { speaker: '画面', text: '凳子边缘粘着一张半透白的糯米纸。' },
                { speaker: '玩家', text: '是制作血包用的糯米纸。' },
                { speaker: '玩家', text: '有人在戏房拆过血包，是为了下毒吗？还是…' },
                { speaker: '玩家', text: '先整理一下目前收集到的信息吧。' },
              ],
              next: true,
            },
          ],
        },
        {
          type: 'hotspot',
          prompt: '把物证摆到桌上整理',
          hotspots: [
            {
              id: 'evidence-table',
              label: '整理证物',
              x: 0.18,
              y: 0.35,
              w: 0.36,
              h: 0.15,
              result: [
                { speaker: '画面', text: '糯米纸、有红泥的鞋子、装着血包的木匣、茶、梅子一一出现在桌子上。' },
                { speaker: '玩家', text: '茶底的黑渣暂时不明，需要带回寺里再行查验。' },
                { speaker: '玩家', text: '有人动过专门给这出戏使用的血包，每个进过戏房的人都有嫌疑…' },
                { speaker: '玩家', text: '可是，糯米纸偏偏在谢无咎的专座上，是他自己动的？' },
                { speaker: '玩家', text: '小乙说，绯萤改了走位，谢无咎看见后还笑了一下，像是早就知道…' },
                { speaker: '昭雪', text: '吱吱吱吱！' },
                { speaker: '玩家', text: '好啦好啦，我知道你闻不惯这里的脂粉味，再忍忍。' },
              ],
              next: true,
            },
          ],
        },
        {
          type: 'hotspot',
          prompt: '继续思考',
          hotspots: [
            {
              id: 'continue-thinking',
              label: '桌子',
              x: 0.18,
              y: 0.35,
              w: 0.36,
              h: 0.15,
              result: [
                { speaker: '玩家', text: '谢无咎和绯萤之间存在着某种默契，有什么只有他们两人知道的事情？' },
                { speaker: '玩家', text: '掌柜刚刚暧昧不明的态度也很可疑，是怕小乙说什么？' },
                { speaker: '玩家', text: '有用的线索太少了，还需要再收集一些线索才行。' },
                { speaker: '玩家', text: '现场其它鞋子上都没有红泥，等他们回来看看能不能问出什么。' },
                { speaker: '画面', text: '你让手下将除了戏鞋以外的证物都带回了大理寺。片刻后，掌柜和小乙端着茶回到了戏房。' },
              ],
              next: true,
            },
          ],
        },
      ],
    },
    {
      id: 'backstage-red-mud',
      title: '倚云楼 · 红泥戏鞋',
      placeLabel: '一只不属于倚云楼的鞋',
      visual: 'ch2-prop-rack-red-mud',
      palette: ['#211d1b', '#6b352b', '#d0a05f'],
      notes: ['红泥来自后巷', '鞋底无云纹', '外人来过'],
      steps: [
        {
          type: 'hotspot',
          prompt: '查看刚端来的热茶',
          hotspots: [
            {
              id: 'hot-tea',
              label: '热茶',
              x: 0.24,
              y: 0.36,
              w: 0.2,
              h: 0.12,
              result: [
                { speaker: '小乙', text: '呀，姐姐你的手沾了红泥，脏了，我帮你擦擦。' },
                { speaker: '玩家', text: '没事，应该是刚才捡那只戏鞋时沾上的。你们这怎么会有泥？' },
                { speaker: '小乙', text: '后巷那边最近修过沟，挖出来的土就是这种颜色。' },
                { speaker: '玩家', text: '你知道得还挺清楚。' },
                { speaker: '小乙', text: '我昨天替师傅跑腿，从后巷经过看到的。' },
                { speaker: '玩家', text: '找个机会支开掌柜，看看能不能从小乙那问出点什么。' },
              ],
              next: true,
            },
          ],
        },
        {
          type: 'hotspot',
          prompt: '让昭雪讨加餐，支开掌柜',
          hotspots: [
            {
              id: 'zhaoxue-snack',
              label: '昭雪',
              x: 0.62,
              y: 0.58,
              w: 0.18,
              h: 0.14,
              result: [
                { speaker: '昭雪', text: '吱。吱吱！' },
                { speaker: '玩家', text: '刚才说加餐，你倒记得清楚。' },
                { speaker: '小乙', text: '它真听得懂啊？' },
                { speaker: '玩家', text: '熟肉。最好切薄些，不要太肥，七分瘦最好。' },
                { speaker: '玩家', text: '掌柜，大理寺来你的地盘办案，总要有点规矩。' },
                { speaker: '掌柜', text: '沈司案，楼里上下现在人心惶惶，怕是一时——' },
                { speaker: '玩家', text: '你们倚云楼号称长安第一楼，不至于连一碟熟肉都取不来吧。' },
                { speaker: '掌柜', text: '自然取得来。小乙……' },
                { speaker: '玩家', text: '等等，劳烦掌柜亲自去一趟。昭雪嘴刁，旁人不会挑。' },
                { speaker: '掌柜', text: '……我这就去取。' },
                { speaker: '玩家', text: '趁掌柜不在，再仔细问问小乙。' },
              ],
              next: true,
            },
          ],
        },
        {
          type: 'hotspot',
          prompt: '追问小乙红泥戏鞋',
          hotspots: [
            {
              id: 'ask-red-mud',
              label: '小乙',
              x: 0.62,
              y: 0.42,
              w: 0.2,
              h: 0.22,
              result: [
                { speaker: '玩家', text: '小乙，刚才你说，红泥是后巷的。' },
                { speaker: '玩家', text: '可戏房里这么多人来来去去，怎么偏只有这只鞋沾了？' },
                { speaker: '小乙', text: '唔……对哦！好奇怪！' },
                { speaker: '小乙', text: '楼里的戏鞋不该沾上红泥，上台鞋都是软底，平日收在箱里，不能穿去后巷。' },
                { speaker: '玩家', text: '你再仔细看看。' },
              ],
              next: true,
            },
          ],
        },
        {
          type: 'inspect',
          prompt: '翻看地上的戏鞋',
          completeText: '戏鞋疑点已确认',
          hotspots: [
            {
              id: 'shoe-upper',
              label: '鞋面',
              x: 0.34,
              y: 0.62,
              w: 0.22,
              h: 0.1,
              clue: '鞋里没有倚云楼红线。',
              result: [
                { speaker: '小乙', text: '这不是我们楼里的鞋！' },
                { speaker: '玩家', text: '你怎么知道这不是？' },
                { speaker: '小乙', text: '倚云楼的鞋里都会用红线缝一道，区分跟其他客人的鞋。' },
                { speaker: '玩家', text: '确实没有…不过缝线也有可能脱落。' },
              ],
            },
            {
              id: 'shoe-sole',
              label: '鞋底',
              x: 0.58,
              y: 0.62,
              w: 0.22,
              h: 0.1,
              clue: '鞋底无云纹，却沾着后巷红泥。',
              result: [
                { speaker: '小乙', text: '真的不是！倚云楼的鞋，鞋底会有特殊的云朵纹。' },
                { speaker: '小乙', text: '而且这鞋是软底的！' },
                { speaker: '玩家', text: '有人穿着它从后巷进来，假装自己是倚云楼的人。' },
                { speaker: '小乙', text: '姐姐的意思是，有外人来过？' },
              ],
            },
          ],
          after: [
            { speaker: '画面', text: '线索：有外人从后巷进入戏房，试图伪装成楼里的人。' },
          ],
        },
        {
          type: 'hotspot',
          prompt: '小乙好像想起了什么',
          hotspots: [
            {
              id: 'xiaoyi-memory',
              label: '小乙',
              x: 0.62,
              y: 0.42,
              w: 0.2,
              h: 0.22,
              result: [
                { speaker: '小乙', text: '姐姐，我想起来，我今天在妆阁里，遇见过一个奇怪的人。' },
                { speaker: '玩家', text: '怎么奇怪？' },
                { speaker: '小乙', text: '他穿着不合身的绯衣，头发遮着脸。' },
                { speaker: '小乙', text: '从外头进来，借小门去了妆阁。' },
              ],
              next: true,
            },
          ],
        },
      ],
    },
    {
      id: 'backstage-dressing-door',
      title: '倚云楼 · 妆阁门前',
      placeLabel: '三年前绯衣娘子的独用妆阁',
      visual: 'ch2-dressing-door',
      palette: ['#1c171a', '#542b32', '#c9945f'],
      notes: ['小门紧闭', '昭雪钻入', '妆阁将启'],
      steps: [
        {
          type: 'hotspot',
          prompt: '查看关着的小门',
          hotspots: [
            {
              id: 'dressing-room-door',
              label: '妆阁小门',
              x: 0.48,
              y: 0.18,
              w: 0.24,
              h: 0.42,
              result: [
                { speaker: '画面', text: '昭雪用头顶开一条缝，灵巧地钻了进去。' },
                { speaker: '小乙', text: '哎呀！它怎么进去了！' },
                { speaker: '玩家', text: '里面是什么地方？' },
                { speaker: '小乙', text: '那就是妆阁！三年前绯衣娘子独用的妆阁！' },
              ],
              next: true,
            },
          ],
        },
        {
          type: 'ending',
          title: '第二章结束',
          text: '第二章结束。下一步将进入妆阁，追查穿着不合身绯衣的陌生人。',
        },
      ],
    },
  ],
};

STORY_DATA.chapters = [
  {
    id: 'chapter-1',
    title: '第一章 · 绯衣鬼戏',
    subtitle: '戏台命案与鬼掐喉疑云',
    scenes: STORY_DATA.scenes,
  },
  CHAPTER_TWO,
];

export default STORY_DATA;
